FROM python:3.7.2

COPY fonts/* /usr/share/fonts/truetype/
RUN apt-get update && apt-get install -y ttf-liberation && fc-cache

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .